pull_request_template.md
> - Adds PR template
> -
- [N/A] Code reviewed
- [N/A] Tests written
- [N/A] SimpleCov at 100% (if not list the percent)
- [N/A] Will this break anything?
> -
=> Chore: adds PR template

.gitignore, Gemfile.lock, Procfile
> - Add configuration requirements to integrate with Heroku:  https://escapelink-be-42ffc95e6cf7.herokuapp.com
> - Added '/coverage/*' to .gitignore for SimpleCov reports
> - Model Tests and Models should be ready for development
=> fix:  add configuration requirements

.circleci/config.yml, Gemfile.lock
> - Add CircleCi configuration
> -
> - Still a skeleton app with no features or functionality yet
=> chore: configure circleci

Gemfile, Gemfile.lock, app/channels/application_cable/channel.rb, app/channels/application_cable/connection.rb, app/channels/game_channel.rb, app/controllers/api/v0/messages_controller.rb, app/models/channel.rb, app/models/message.rb, config/initializers/cors.rb, config/routes.rb, db/migrate/20231015185349_create_channels.rb, db/migrate/20231015185355_create_messages.rb, db/schema.rb, spec/factories.rb, spec/models/message_spec.rb, spec/rails_helper.rb, spec/requests/api/v0/messages_spec.rb
> - Adds websocket chat and nickname setting functionality as well as tests.
> -
> - As of now, the frontend functionality for this can be seen at this URL: https://github.com/MWoodshop/websocket_channels_fe
=> Add websockets chat

config/environments/production.rb
> - Adds localhost to action_cable allowed requests. NOTE: change to FE once FE is deployed.
> -
> -
=> Chore: updated to use localhost FE for testing

README.md
> - Add a README template and begin working on it.
> -
> - THIS IS NOT DONE - THIS IS A SKELETON. I will work on it more as the project progresses 😄
=> docs: add readme template

app/models/leaderboard.rb, db/migrate/20231016173711_create_leaderboard.rb, db/schema.rb, spec/models/leaderboard_spec.rb
> - Create tests, model, and database for Leaderboard.  This includes the group_name and time_seconds for easy top-10 comparison.  The date for the leaderboard will be the automatic creation date.  This can be adjusted later if needed.
> - No
> -
=> 13 configure leaderboard database

app/controllers/api/v0/games_controller.rb, app/models/game.rb, app/models/game_puzzle.rb, app/models/leaderboard.rb, app/models/puzzle.rb, app/models/room.rb, db/migrate/20231014184911_create_games.rb, db/migrate/20231016173711_create_leaderboard.rb, db/migrate/20231017195657_remove_puzzle1_solved_from_games.rb, db/migrate/20231017200005_add_start_time_to_games.rb, db/migrate/20231018000637_create_rooms.rb, db/migrate/20231018003614_create_puzzles.rb, db/migrate/20231018004049_create_game_puzzles.rb, db/migrate/20231018004612_add_foreign_key_to_leaderboards.rb, db/migrate/20231018175253_update_games_with_new_structure.rb, db/schema.rb, spec/factories/leaderboard.rb, spec/models/game_puzzle_spec.rb, spec/models/game_spec.rb, spec/models/leaderboard_spec.rb, spec/models/puzzle_spec.rb, spec/models/rooms_spec.rb, spec/requests/api/v0/games_spec.rb
> - Refactor database schema based on feedback from our Project Manager
> - Changed how some methods are called, adding labels to method attributes
> - This was a big lift-n-shift, requiring modification of all Tests, Models, and the API Controller
=> 20.1 create one to many database games to puzzles

config/environments/production.rb, config/initializers/cors.rb
> - Adds URL for front end deployment.
> - No
> -
=> Chore: adds FE deployment credentials

app/controllers/application_controller.rb
=> Chore: adds Cors to application_controller

config/environments/production.rb
=> Chore: removes trailing slash

config/environments/production.rb, config/initializers/cors.rb
=> Revert to localhost

app/controllers/application_controller.rb
> - Returns to localhost URLs for development.
> -
> -
=> Chore: returns to default localhost

app/controllers/api/v0/games_controller.rb, db/seeds.rb, spec/requests/api/v0/games_spec.rb
> - Update Start Game API to require game_name as a parameter
:  /api/v0/games?room_name=Where's Bob?
> - Updated tests accordingly
> -
=> Fix game start api

app/models/game.rb, app/models/game_puzzle.rb, app/models/puzzle.rb, db/migrate/20231019193507_add_puzzle_identifier_to_puzzles.rb, db/schema.rb, db/seeds.rb, spec/models/game_puzzle_spec.rb, spec/models/puzzle_spec.rb
> - create methods for updating a puzzle and generating game puzzles
> - No
> - 🤾
=> Update game state

app/models/game.rb, spec/models/game_puzzle_spec.rb, spec/models/game_spec.rb, spec/models/leaderboard_spec.rb
> - add methods for timer, update tests, write new tests
> - No
> -
=> Timer methods 3

.gitignore, app/channels/data_channel.rb, config/routes.rb
> - Adds data channel for websockets to the front end regarding puzzle completion.
> - No
> - Negative
=> Add data channel

app/channels/data_channel.rb, app/models/game.rb, app/models/game_puzzle.rb, spec/channels/data_channel_spec.rb
> - Establish DataChannel communication:  Trigger "Puzzle X Solved" updates, check for game completion, render "Game Over: true/false" broadcast, trigger end-of-game teardown when ready.
> - No
- [ X] Code reviewed
- [ X] Tests written
- [ X] SimpleCov at 100% (if not list the percent)
> - This is the last of the features, all tests complete.
=> Websocket conn

config/environments/production.rb, config/initializers/cors.rb
> - Changes credentials back to Vercel for final deployment.
> -
> -
=> Chore: changes credentials back to Vercel

config/environments/production.rb, config/initializers/cors.rb
> - Adds localhost to cors.
> -
> -
=> Chore: adds localhost to cors

config/environments/production.rb, config/initializers/cors.rb
> - Adds localhost back to CORS to pass tests on FE.
> -
> -
=> Chore: adds localhost to cors to pass testing on FE

README.md
> Update Readme with Leaderboard example data
> -
- [ X] Tests written
- [ X] SimpleCov at 100% (if not list the percent)
> -
=> doc: update readme with leaderboard example
